version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
    volumes:
      - .:/app
    command: uvicorn main:app --reload --port=8000 --host=0.0.0.0
